Se agregaron departamentos a profesores y departamentos
Juanfg/novusPev pull request #13
Opened 2017-02-21 18:42 UTC by Julian943

2017-03-01 20:36 UTC, Juanfg requested changes

2017-03-01 20:36 UTC, Juanfg commented on novusPev/composer.lock
>          "Read more about it at https://getcomposer.org/doc/01-basic-usage.md#composer-lock-the-lock-file",
Hiciste composer update?
Agregaste algo en especial? 
@Julian943

2017-03-01 21:01 UTC, Juanfg approved these changes

2017-03-01 21:02 UTC, merged

2017-03-02 16:58 UTC, Julian943 commented on novusPev/composer.lock
>          "Read more about it at https://getcomposer.org/doc/01-basic-usage.md#composer-lock-the-lock-file",
nope